language: node_js

node_js:
    - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -- version 0.23.2
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
    - yarn install

script:
    - yarn run build

cache:
    directories:
        - "node_modules"

deploy:
    provider: pages
    skip-cleanup: true
    local_dir: build
    github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    target-branch: $P_BRANCH
    on:
        branch: master

branches:
  only:
    - master
